on:
  push:
  pull_request:
    branches:
      - master

jobs:
  action/directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Targets the specified directory
        uses: ./
        with:
          directory: 'tests/action/directory/*'

      - name: Compare the minified files
        run: |
          git diff --exit-code
