name: Test workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  action:
    name: "Tests the action inputs"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Targets the specified directory"
            with:
              directory: 'tests/action/directory/*'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: ${{ matrix.name }}
        uses: ./
        with:
          directory: ${{ matrix.with.directory }}

      - name: Compare the minified files
        run: git diff --exit-code
