name: Test workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - test: directory
            params:
              directory: 'tests/action/directory/*'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Targets the specified directory
        uses: ./
        with: ${{ toJSON(matrix.params) }}

      - name: Compare the minified files
        run: git diff --exit-code
