name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Targets specific directory
        uses: ./
        with:
          directory: "tests/action/directory/a/*"

      - name: Compare the minified files
        run: git diff --exit-code
