name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test on affected directory
        uses: ./
        with:
          directory: "tests/directory/affected"

      - name: Assert not affected result does not exist
        run: |
          ! test -e tests/directory/not-affected/main.min.js

      - name: Assert affected result matches expected
        run: |
          git diff --exit-code --no-index \
            tests/directory/affected/main.expected.js \
            tests/directory/affected/main.min.js

  maxdepth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test on shallow maxdepth
        uses: ./
        with:
          directory: "tests/maxdepth"
          maxdepth: 1

      - name: Assert shallow result matches expected
        run: |
          git diff --exit-code --no-index \
            tests/maxdepth/main.expected.js \
            tests/maxdepth/main.min.js

      - name: Assert deep result does not exist
        run: |
          ! test -e tests/maxdepth/not-affected/main.min.js

  overwrite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test overwrite
        uses: ./
        with:
          directory: "tests/overwrite"
          overwrite: true

      - name: Assert overwrite result matches expected
        run: |
          git diff --exit-code --no-index \
            tests/overwrite/main.expected.js \
            tests/overwrite/main.js

  output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Test output
        uses: ./
        with:
          directory: "tests/output"
          output: "tests/output/prod/js"

      - name: Assert output directory is created
        run: |
          test -d tests/output/prod/js

      - name: Assert output result matches expected
        run: |
          git diff --exit-code --no-index \
            tests/output/main.expected.js \
            tests/output/prod/js/main.min.js
