on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  action/directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Targets the specified directory
        uses: nizarmah@auto-minify
        with:
          directory: 'tests/action/directory/*'

      - name: Compare the minified files
        run: |
          git diff --exit-code
